### ISSUE TITLE
End date for initial admins with AccessRules

### ISSUE THREAD

**Issue by stdavis** [agrc/ArcGisServerPermissionsProxy#70]
When an application is created with access rules the initial admins' end dates are set to 0, which prevents them from logging in.

Proposed solutions:
- Set the end dates to something like -1 and make that a key to allow them access indefinitely.
- Set the end date to some date far into the future that is sure to be past the end of the applications life.

**Comment by steveoh** [comment]
@stdavis thoughts on those 2 commits before I rebase to master and version bump?

**Comment by stdavis** [comment]
Looks great to me. Thanks!
